# Generated by Django 4.2 on 2023-05-01 13:02

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_title', unique=True)),
                ('product_desc', models.TextField()),
                ('product_price', models.IntegerField()),
                ('product_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_stock', models.IntegerField()),
                ('product_brand', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=100)),
                ('product_thumbnail', models.URLField()),
                ('product_images', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
