# Generated by Django 4.2 on 2023-05-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
